---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Install nginx configuration
  template:
    src: default.conf
    dest: "{{ nginx_conf }}"
    mode: 0755

- name: start service nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes

- name: add rule for firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: restart service firewall
  systemd:
    name: firewalld
    daemon_reload: yes

- name: Disable SELinux
  selinux:
    state: disabled

- name: Unconditionally reboot the machine with all defaults
  reboot:

