---
# tasks file for deploy_tomcat_web
- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home="{{ tomcat_home }}" createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.19/bin/apache-tomcat-9.0.19.tar.gz dest=/opt/apache-tomcat-9.0.19.tar.gz

- name: Create directory
  file:
    path=/opt/tomcat
    mode=0755
    owner=root
    group=root
    state=directory

- name: Extract archive
  unarchive:
    src: /opt/apache-tomcat-9.0.19.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configure Tomcat service
  template:
    src: tomcat.service 
    dest: "{{ tomcat_service }}" 
    mode: 0755
  notify:
    - restart tomcat 

- name: Configure Tomcat users
  template: 
    src: tomcat-users.xml 
    dest: "{{ tomcat_conf }}"
    mode: 0755
  notify:
    - restart tomcat

- name: Configure Tomcat context
  template: 
    src: context.xml
    dest: "{{ tomcat_context }}"
    mode: 0755
  notify:
    - restart tomcat

- name: Configure Tomcat server
  template:
    src: server.xml
    dest: "{{ tomcat_conf }}"
    mode: 0755
  notify:
    - restart tomcat

- name: Start and enabled Tomcat service
  systemd:
    name: tomcat 
    state: started 
    enabled: true
    daemon_reload: true
