---

- name: Create Database for SonarQube
  postgresql_db:
    name: '{{ psql_sonar_db }}'
    encoding: UTF-8
  become: true

- name: Create Sonar User
  postgresql_user:
    db: '{{ psql_sonar_db }}'
    name: '{{ sonar_postgres_username }}'
    password: '{{ sonar_postgres_password }}'
    priv: ALL
  become: true