---
- name: Install java 11
  yum:
    name: "java-11-openjdk-devel"
    state: present
  become: true

- name: install packages PostgreSQL
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: latest
  become: true

- name: Install PostgreSQL
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - postgresql10-server
    - postgresql10-contrib
  become: true
  register: installed_psql

- name: Intialize PostgreSQL DB
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  become: true
  when: installed_psql.changed

- name: Set Postgres database conf
  template:
    src: pg_hba.conf
    dest: "{{ postgres_conf }}"
    owner: postgres
    group: postgres
    mode: 0755

- name: Enable and Start PostgreSQL
  service:
    name: postgresql-10
    state: started
    enabled: yes
  become: true

- name: Execute cmd
  shell: sysctl -w vm.max_map_count=262144 & sysctl -w fs.file-max=65536 & ulimit -n 65536 & ulimit -u 4096

- name: Sleep for 60 seconds and continue with play
  wait_for: timeout=60

- name: Change password for user postgres
  shell: echo "Passwd0rD" | passwd --stdin postgres
