---
- name: Install PostgreSQL RPM
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: latest

- name: Install PostgreSQL
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - postgresql10-server
    - postgresql10-contrib
  become: true
  register: installed_psql

- name: Intialize PostgreSQL DB
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  become: true

- name: Sleep for 20 seconds and continue with play
  wait_for: timeout=20

- name: Copies correct PostgreSQL config file over
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/10/data/
    owner: root
    group: root
    mode: 0755

- name: Enable and Start PostgreSQL
  service:
    name: postgresql-10
    state: started
    enabled: yes
  become: true
