---
- name: Install java 11
  yum:
    name:
      - java-11-openjdk-devel
    state: present

- name: install repo for PostgreSQL
  yum:
    name: "{{ postgreSQL_repo }}"
    state: present

- name: install PostgreSQL
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Enscure database postgres
  yum:
    name:
      - postgresql10-server
      - postgresql10-contrib
    state: present

- name: Init the Postgres database
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: Set Postgres database conf
  template:
    src: pg_hba.conf
    dest: "{{ postgres_conf }}"
    mode: 0755

- name: Execute cmd
  shell: sysctl -w vm.max_map_count=262144 & sysctl -w fs.file-max=65536 & ulimit -n 65536 & ulimit -u 4096

- name: Change password for user postgres
  shell: echo "Passwd0rD" | passwd --stdin postgres

- name: postgresql | Create sonar postgresql user
  postgresql_user:
    name: "{{ sonar_postgres_username }}"
    password: "{{ sonar_postgres_password }}"
  notify: restart sonar

- name: Create a new database with name "sonarqube"
  postgresql_db:
    name: sonarqube
    owner: "{{ sonar_postgres_username }}"
    priv: ALL
  notify: restart sonar
