---
- name: Install java 11
  yum:
    name: "java-11-openjdk-devel"
    state: present
  become: true

- name: install packages PostgreSQL
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/postgresql96-libs-9.6.18-1PGDG.rhel7.x86_64.rpm
    state: present
  become: true

- name: install server PostgreSQL
  yum:
    name: "{{ postgreSQL_server }}"
    state: present
  become: true

- name: install server PostgreSQL
  yum:
    name: "{{ postgreSQL_contrib }}"
    state: present

- name: Install PostgreSQL
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - postgresql96-server
    - postgresql96-contrib
  become: true
  register: installed_psql

- name: Intialize PostgreSQL DB
  command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  become: true
  when: installed_psql.changed

- name: Set Postgres database conf
  template:
    src: pg_hba.conf
    dest: "{{ postgres_conf }}"
    owner: postgres
    group: postgres
    mode: 0755

- name: Enable and Start PostgreSQL
  service:
    name: postgresql-9.6
    state: started
    enabled: yes
  become: true

- name: Execute cmd
  shell: sysctl -w vm.max_map_count=262144 & sysctl -w fs.file-max=65536 & ulimit -n 65536 & ulimit -u 4096

- name: Sleep for 60 seconds and continue with play
  wait_for: timeout=60

- name: Change password for user postgres
  shell: echo "Passwd0rD" | passwd --stdin postgres
