---
- name: Install PostgreSQL RPM
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: latest

- name: Install PostgreSQL
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - postgresql10-server
    - postgresql10-contrib
  become: true
  register: installed_psql

- name: Intialize PostgreSQL DB
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  become: true
  when: installed_psql.changed

- name: Copies correct PostgreSQL config file over
  copy:
    src: pg_hba.conf
    dest: /var/lib/pgsql/10/data/pg_hba.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Enable and Start PostgreSQL
  service:
    name: postgresql-10
    state: started
    enabled: yes
  become: true
