---
- name: Extract Sonar
  unarchive:
    src: "{{ sonar_download_url }}"
    dest: "/opt/"
    remote_src: yes
    mode: 0755

- name: Sonar rename
  shell: mv /opt/{{ sonar_version_directory }} {{ sonar_home }}

- name: Set Unit for Sonar
  template:
    src: sonar.service
    dest: "{{ sonar_unit }}"
    mode: 0755

- name: Set sysctl ram for Sonar
  template:
    src: sysctl.conf
    dest: "/etc/"
    mode: 0755

- name: Set Properties for Sonar
  template:
    src: sonar.properties
    dest: "{{ sonar_properties }}"
    mode: 0755

- name: Set RUN with user service Sonar
  template:
    src: sonar.sh
    dest: "{{ sonar_properties }}"
    mode: 0755

- name: Set vm.max_map
  shell: "sysctl -w vm.max_map_count=262144"