---

- name: install repo for PostgreSQL
    yum:
      name: "{{ postgreSQL_repo }}"
      state: present

- name: install PostgreSQL
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - postgresql94-server
      - postgresql94-contrib

- name: Init the Postgres database
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: Set Postgres database conf
  template:
    src: pg_hba.conf
    dest: "{{ postgre_conf }}"
    mode: 0755

- name: Execute cmd
  shell: sysctl -w vm.max_map_count=262144 & sysctl -w fs.file-max=65536 & ulimit -n 65536 & ulimit -u 4096

- name: Change password for user postgres
  shell: echo "Passwd0rD" | passwd --stdin postgres

- name: postgresql | Create sonar postgresql user
  postgresql_user:
    name: {{ sonar_postgres_username }}
    password: {{ sonar_postgres_password }}
  sudo_user: postgres
  notify: restart sonar

- name: Create a new database with name "sonarqube"
  postgresql_db:
    name: sonarqube
    owner: {{ sonar_postgres_username }}
    priv: ALL
  sudo_user: postgres
  notify: restart sonar
