---
- name: add group "sonar"
  group: name={{ sonar_group }}

- name: add users "sonar"
  user: name={{ sonar_user }} group={{ sonar_group }} home="{{ sonar_home }}" createhome=no

- name: Add own directory sonar
  shell: chown -R {{ sonar_user }}:{{ sonar_user }} {{ sonar_home }}

- include_tasks: install Sonar.yml

- name: Start service Postgres
  systemd:
    name: postgresql-10
    state: started
    enabled: yes
    daemon_reload: yes

- include_tasks: install Postgres database.yml

- name: Add rule for sonar port
  firewalld:
    port: "{{ sonar_port }}/tcp"
    permanent: yes
    state: enabled
    notify:
      - restart sonar