---
# tasks file for sonarqube
- name: add group "sonar"
  group: name={{ tomcat_group }}

- name: add users "sonar"
  user: name={{ sonar_user }} group={{ sonar_group }} home="{{ sonar_home }}" createhome=no

- include_tasks: install Postgres database.yml

- name: Start service Nexus
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes