---

- name: GRAFANA | Ensure grafana group
  group:
    name: "{{ grafana_group }}"

- name: grafana | Ensure grafana user
  user:
    name: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    shell: /bin/bash

- name: GRAFANA | Installing dependencies
  yum:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ grafana_required_libs }}"
  tags:
    skip_ansible_lint

- name: GRAFANA | CentOS repo key on package cloud
  rpm_key:
    key: "{{ grafana_key }}"
    state: present

- name: GRAFANA | CentOS grafana repo
  template:
    src: grafana.repo
    dest: "{{ grafana_repo }}"
    mode: 0755

- name: GRAFANA | Install grafana
  yum:
    name: grafana
    state: latest

- name: Links grafana dir to /
  file:
    src: /etc/grafana
    dest: /grafana
    state: link
    force: yes
