---
# vars file for nexus

nexus_home: /opt/nexus
nexus_config: "{{ nexus_home }}/etc/"
nexus_unit: /etc/systemd/system/
nexus_data: /opt/nexusdata

nexus_version: nexus-3.24.0-02-unix
nexus_web: https://download.sonatype.com/nexus/3/{{ nexus_version }}.tar.gz

nexus_ip: 192.168.88.228
nexus_port: 8081
nexus_context: /nexus
nexus_user: nexus
nexus_group: nexus