---

- hosts: dev
  remote_user: "{{ vault_ansible_ssh_user }}"

  tasks:
    - name: Run a command using a templated variable (always use quote filter to avoid injection)
      shell: date
      register: date

    - name: Touch the same file, but add/remove some permissions
      file:
        path: "/{{ vault_ansible_ssh_user }}/test.txt"
        state: touch
        mode: u+rw,g-wx,o-rwx
        
    - name: Add a line to a file if the file does not exist, without passing regexp
      ansible.builtin.lineinfile:
        path: /opt/prometheus.yml
        line: "    - post1"
        create: yes
        
    - name: node
      command: sed  -i "/cat/ { N; s/    - test:9100\n/    - test2:9100\n&/ }" /opt/prometheus.yml

    - name: Check created file in system
      shell: ls
      register: ls

    - name: Check date
      debug:
        var: date.stdout

    - name: Check file
      debug:
        var: ls.stdout_lines
