---
# This playbook deploys a simple standalone Tomcat 9 server.

- hosts: Linux1
  remote_user: root

  roles:
   - install_packages
   - java
   - nginx
   - jenkins
   - nexus
   - sonarqube
   - tomcat
   - wildfly
