---
# tasks file for wildfly

- name: Create management users
  shell: >
    {{ wildfly_home }}/bin/add-user.sh -s
    {{ management_user }} {{ management_password }} && touch {{ wildfly_dir }}/.mgmt-users.{{ management_user }}.provisioned
  become: True
  become_user: '{{ wildfly_user }}'
  args:
    creates: "{{ wildfly_home }}/.mgmt-users.{{ management_user }}.provisioned"
  when: wildfly_management_users | length > 0

- name: Create application users
  shell: >
    {{ wildfly_dir }}/bin/add-user.sh -s -a
    {{ app_user }} {{ app_password }} && touch {{ wildfly_home }}/.app-users.{{ app_user }}.provisioned
  with_items: "{{ wildfly_app_users }}"
  become: True
  become_user: '{{ wildfly_user }}'
  args:
    creates: "{{ wildfly_dir }}/.app-users.{{ app_user }}.provisioned"
  when: wildfly_app_users | length > 0

- name: Enforce secure permissions on password files
  file:
    path: "{{ wildfly_home }}/standalone/configuration/{{ item }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: "0600"
  with_items:
    - mgmt-groups.properties
    - mgmt-users.properties