---
# tasks file for wildfly

- name: Create management users
  shell: >
    {{ wildfly_home }}/bin/add-user.sh -s {{ item.name }} {{ item.password }}
  with_items: "{{ wildfly_management_users }}"
  become: True
  become_user: '{{ wildfly_user }}'

- name: Create application users
  shell: >
    {{ wildfly_home }}/bin/add-user.sh -s -a {{ item.name }} {{ item.password }}
  with_items: "{{ wildfly_app_users }}"
  become: True
  become_user: '{{ wildfly_user }}'

- name: Enforce secure permissions on password files
  file:
    path: "{{ wildfly_home }}/standalone/configuration/{{ item }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: "0600"
  with_items:
    - mgmt-groups.properties
    - mgmt-users.properties