---
- name: Add rule on read admin_password
  shell: chmod 755 /opt/nexusdata/nexus3/admin.password

- name: View the admin password is created and stored in the log file
  shell: more /opt/nexusdata/nexus3/admin.password
  register: passwd

- name: Check admin password
  debug:
    var: passwd