---
- name: Add rule on read admin_password
  file:
    path: /opt/nexusdata/nexus3/admin.password
    owner: nexus
    group: nexus
    mode: '0755'

- name: View the admin password is created and stored in the log file
  shell: more /opt/nexusdata/nexus3/admin.password
  register: passwd

- name: Check admin password
  debug:
    var: passwd.stdout_lines