---
- name: Extract Nexus
  unarchive:
    src: "{{ nexus_web }}"
    dest: "/opt/"
    remote_src: yes
    mode: 0755

- name: Remove Nexus archive
  file:
    path: "/opt/{{ nexus_version }}.tar.gz"
    state: absent

- name: Nexus rename
  shell: mv /opt/nexus-3.* {{ nexus_home }}

- name: Nexusdata rename
  shell: mv /opt/sonatype-work /opt/nexusdata