---
# tasks file for nexus
- include_tasks: Install nexus.yml

- name: Adding user {{ nexus_user }}
  user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    append: yes
  ignore_errors: yes

- include_tasks: Configure nexus.yml

- name: Add own directory nexus
  shell: chown -R {{ nexus_user }}:{{ nexus_user }} {{ nexus_home }}

- name: Add own directory nexusdata
  shell: chown -R {{ nexus_user }}:{{ nexus_user }} {{ nexus_data }}

- name: Set Nexus as a System Service
  template:
    src: nexus.service
    dest: "{{ nexus_unit }}"
    mode: 0755

- name: Start service Nexus
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add rule on firewall for Nexus
  firewalld:
    port: "{{ nexus_port }}/tcp"
    permanent: yes
    state: enabled
  notify:
    - restart nexus

- include_tasks: Check admin password.yml