---
# vars file for sonarqube

#### Sonar version ####
# (https://binaries.sonarsource.com/Distribution/sonarqube/)
#### 4 ####
#### 5 ####
#### 6 ####
#### 7 ####
#### 8 ####
#### ------------- ####

sonar_user: sonar
sonar_group: sonar
sonar_home: /opt/sonarqube


# Set Config
sonar_unit: /etc/systemd/system/
sonar_properties: "{{ sonar_home}}/conf/"
sonar_run_user: "{{ sonar_home/bin/linux-x86-64/}}"


sonar_version: 8.0
sonar_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonar_version }}.zip"
sonar_version_directory: "sonarqube-{{ sonar_version }}"

# For sonar.properties
sonar_web_context: /sonar
sonar_web_host: 0.0.0.0
sonar_port: 9000

postgreSQL_server: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/postgresql96-libs-9.6.18-1PGDG.rhel7.x86_64.rpm
postgreSQL_contrib: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/postgresql96-contrib-9.6.18-1PGDG.rhel7.x86_64.rpm

postgres_conf: /var/lib/pgsql/10/data/pg_hba.conf

# Postgres database connection details.
psql_sonar_db: sonarqube
sonar_postgres_username: sonar
sonar_postgres_password: sonar
sonar_jdbc_url: jdbc:postgresql://localhost/sonar



