---

- name: View the admin password is created and stored in the log file
  shell: grep -A 5 password {{ jenkins_log }}
  register: passwd

- name: Check admin password
  debug:
    var: passwd.stdout_lines