---
# tasks file for jenkins
- include_tasks: Install a list of packages.yml

- name: Ensure Jenkins Repository is Installed
  shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo

- name: install the jenkins rpm from a remote repo
  yum:
    name: https://pkg.jenkins.io/redhat-stable/jenkins-2.222.4-1.1.noarch.rpm
    state: present

- name: Ensure JAVA is installed
  command: java -version
  register: prereq_java
  changed_when: false

- name: Ensure Jenkins is Installed
  yum :
    name: jenkins
    update_cache: yes
    state: present

- name: Configure Jenkins
  template:
    src: jenkins
    dest: "{{ jenkins_config }}"
    mode: 0755
  notify:
    - restart jenkins

- name: Start service Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes

- name: add rule firewall on jenkins_port
  firewalld:
    port: "{{ jenkins_port }}/tcp"
    permanent: yes
    state: enabled
    notify:
      - restart jenkins

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30

- include_tasks: Check admin password.yml