---
# tasks file for jenkins
- include_tasks: Install a list of packages.yml

- name: Importing the repository key from Jenkins
  shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add the repository to the system
  shell: curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo

- name: Ensure JAVA is installed
  command: java -version
  register: prereq_java
  changed_when: false

- name: Install the Jenkins
  yum:
    name: jenkins

- name: Configure Jenkins
  template:
    src: jenkins
    dest: "{{ jenkins_config }}"
    mode: 0755
  notify:
    - restart jenkins

- name: Start service Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes

- firewalld:
    port: "{{ jenkins_port }}/tcp"
    permanent: yes
    state: enabled
    notify:
      - restart jenkins

- include_tasks: Check admin password.yml