---
# tasks file for jenkins
- import tasks: Install a list of packages.yml

- name: Importing the repository key from Jenkins
  shell: rpm --import {{ jenkins-ci-key }}

- name: Add the repository to the system
  shell: wget -O {{ jenkins_repo_in }} {{ jenkins_repo_out }}

- name: Install the Jenkins
  yum:
    name: Jenkins
    state: latest

- name: Configure Jenkins
  template:
    src: jenkins
    dest: {{ jenkins_config }}
    mode: 0755
  notify:
    - restart jenkins

- name: Start service Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes

- firewalld:
    port: {{ jenkins_port }}/tcp
    permanent: yes
    state: enabled
    notify:
      - restart jenkins

- import tasks: Check admin password.yml