---
# tasks file for jenkins
- name: Install a list of packages
  yum:
    name:
      - curl
      - wget
      - net-tools
      - vim
    state: latest

- name: Importing the repository key from Jenkins
  shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add the repository to the system
  shell: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

- name: Install the Jenkins
  yum:
    name: Jenkins
    state: latest

- name: Start service Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes

- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: View the admin password is created and stored in the log file
  shell: grep -A 5 password /var/log/jenkins/jenkins.log
  register: passwd

- name: Check admin password
  debug:
    var: passwd