---
- name: Install a list of packages
  yum:
    name:
      - curl
      - wget
      - net-tools
      - vim
      - unzip
      - deltarpm
    state: latest

- name: upgrade all packages
  yum: name=* state=latest